// Generated by CoffeeScript 1.9.1
(function() {
  define(['mr', 'underscore', 'models/item', 'views/status', 'constants', 'text!templates/control.html'], function(Mr, _, ItemModel, StatusView, constants, controlTpl) {
    return Mr.View.extend({
      template: _.template(controlTpl),
      events: {
        'click #item-add': 'addItem',
        'click #clear-completed': 'removeCompleted',
        'click #complete-all': 'completeAll',
        'keypress #item-title-input': 'addOnEnter'
      },
      initialize: function() {
        this.createNewItem();
        return this.statusView = new StatusView({
          collection: this.collection
        });
      },
      addOnEnter: function(e) {
        this.$('#item-title-input').parent().removeClass('has-error');
        if (e.which === constants.ENTER_KEY) {
          return this.addItem();
        }
      },
      addItem: function() {
        this.newItem.set('title', $('#item-title-input').val().trim());
        if (this.newItem.isValid()) {
          this.collection.add(this.newItem);
          this.newItem.save();
          return this.createNewItem();
        }
      },
      createNewItem: function() {
        if (this.newItem) {
          this.stopListening(this.newItem, 'invalid');
        }
        this.newItem = new ItemModel();
        this.listenTo(this.newItem, 'invalid', this.render);
        return this.$('#item-title-input').val('');
      },
      removeCompleted: function() {
        var completed;
        completed = this.collection.where({
          completed: true
        });
        return completed.map(function(item) {
          return item.destroy();
        });
      },
      completeAll: function() {
        return this.collection.map(function(item) {
          item.set('completed', true);
          return item.save();
        });
      },
      render: function() {
        var error_msg;
        error_msg = this.newItem.validationError ? this.newItem.validationError : false;
        this.$el.html(this.template({
          error: error_msg
        }));
        this.$el.find('#app-status').html(this.statusView.render().el);
        return this;
      }
    });
  });

}).call(this);

//# sourceMappingURL=controller.js.map
